### ISSUE TITLE
Feature Request: (optional) Toolbar Access

### ISSUE THREAD

**Issue by martinmcwhorter** [le0pard/storybook-addon-root-attribute#1]
First of all -- thank for contributing this addon. 

I think this could be improved by providing a dropdown select in the toolbar to select the option, rather than a tab within the addon trays. 

This is something I could potentially create a pull request for if you believe this functionality should be in the addon.

**Comment by le0pard** [comment]
@martinmcwhorter yep, I think it is can be as an option. Let's create PR for this.

**Comment by le0pard** [comment]
Should be resolved in 0.2.0 version
